### ISSUE TITLE
When I update a pledge, the API seems to consider that the updated pledge amount is still used not allowing me to update unless I have twice the credit

### ISSUE THREAD

**Issue by xavigonz** [pledgcorporate/api#1]

**Comment by yangeorget** [comment]
cannot reproduce on www.pledg.co 
can you please list the steps (from login)?

**Comment by xavigonz** [comment]
Example. 20€ credit remaining. I create a pledge of 20€, everything goes ok. However when I try to update the pledge by changing the url for example, the system will indicate that I don't have any credit left, thus not allowing me to update.

**Comment by yangeorget** [comment]
was a bug in web (not in the api): there are some validations there too. can you please check and close?

**Comment by xavigonz** [comment]
Ok. However I'm still getting the error

**Comment by xavigonz** [comment]
I checked it again and it works now
